# Generated by Django 5.2.4 on 2025-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college_of_education', 'College of Education'), ('other', 'Other')], default='university', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
    ]
