# Generated by Django 5.2.4 on 2025-08-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='Check on Google', max_length=100, null=True)),
                ('website', models.CharField(default='Check on Google', max_length=100, null=True, unique=True)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college_of_education', 'College of Education')], default='university', max_length=50)),
                ('ownership_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('private', 'Private')], default='federal', max_length=50)),
                ('year_of_establishment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='Check on Google', null=True)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
    ]
