# Generated by Django 5.2.4 on 2025-08-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_years', models.IntegerField(help_text='Duration in years')),
                ('olevel_requirements', models.TextField(blank=True, help_text='e.g., 5 credits in English, Maths, Physics, Chemistry, Biology', null=True)),
                ('jamb_requirements', models.TextField(blank=True, help_text='e.g., English, Physics, Chemistry, Biology', null=True)),
                ('post_utme_details', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institution')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('institution', 'name')},
            },
        ),
    ]
