# Generated by Django 5.2.4 on 2026-03-20 21:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dvbbvnwkq/image/upload/v1754969274/users/ruzhyrxb2r4goi6vkncs.jpg', max_length=255, null=True, verbose_name='photo'),
        ),
    ]
